# Generated by Django 3.2.7 on 2021-09-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='correct_answers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='empty_answers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='incorrect_answers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='time_taken',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey_api.survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
